[package]
name = "solana_copy_trade_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.11.0"
solana-sdk = "1.11.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
